[env:fast_rk4]
platform = ststm32
board = nucleo_g474re
framework = arduino
build_flags = -Wl,-u_SEGGER_RTT

[env:slow_rk4]
platform = ststm32
board = nucleo_g474re
framework = arduino
build_flags = -Wl,-u_SEGGER_RTT -D SLOW_MODE

[env:fast_fwd_euler]
platform = ststm32
board = nucleo_g474re
framework = arduino
build_flags = -Wl,-u_SEGGER_RTT -D USE_EULER

[env:slow_fwd_euler]
platform = ststm32
board = nucleo_g474re
framework = arduino
build_flags = -Wl,-u_SEGGER_RTT -D SLOW_MODE -D USE_EULER
